name: Build & Test

on:
  push:
    branches: [ "main" ]

env:
  DOTNET_VERSION: "6.x.x"

jobs:
  build:
    name: Build
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Tests
      run: dotnet test -c Release
  
